import type { Metadata } from "next";
import "@/globals.css";
import Navbar from "@/components/Navbar";
import QuickLinks from "@/components/QuickLinks";
import Footer from "@/components/Footer";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`font-body antialiased`}
      >
        <Navbar />
        {/* <QuickLinks /> */}
        {children}
        <Footer />
      </body>
    </html>
  );
}
